// <auto-generated />

using EntityFrameworkDemo.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace EntityFrameworkDemo.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180301113626_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview1-28290");

            modelBuilder.Entity("WpfApp.Core.Domain.Employer", b =>
                {
                    b.Property<int>("EmployerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("EmployerId");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("WpfApp.Core.Domain.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<int?>("Employer1EmployerId");

                    b.Property<string>("Name");

                    b.HasKey("WorkerId");

                    b.HasIndex("Employer1EmployerId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("WpfApp.Core.Domain.Worker", b =>
                {
                    b.HasOne("WpfApp.Core.Domain.Employer", "Employer1")
                        .WithMany("Workers")
                        .HasForeignKey("Employer1EmployerId");
                });
#pragma warning restore 612, 618
        }
    }
}
